### ISSUE TITLE
controller.sh_not_found

### ISSUE THREAD

**Issue by abusm4n** [afmurillo/ICS-SDN#3]
Dear Andres Murillo Piedrahita,
Hope you are doing well. 
I tried simulating this environment but unfortunately the making the fran folder, the ./controller.sh file is not found in the repository, as a results, Unable to contact the remote controller at 192.168.56.100:6633. 
Also when making the paper is says; invalid user:  'mininet:mininet'
Kindly find the screenshots attached.
![Screenshot 2021-02-22 at 1 18 55 PM](https://user-images.githubusercontent.com/39135208/109647144-44b5c100-7b59-11eb-9ef5-9ab9ae1ddd48.png)
![Screenshot 2021-02-22 at 1 07 10 PM](https://user-images.githubusercontent.com/39135208/109647185-4e3f2900-7b59-11eb-951d-b0a43eb10d6b.png)

**Comment by afmurillo** [comment]
Hello,

Sorry for that. I just added the scripts required to run. Could you try again?

**Comment by abusm4n** [comment]
Dear Andres Murillo, that solved the issue, thank you very much

**Comment by afmurillo** [comment]
Ok, closing this issue
